export const SUCCESS_RESPONSES = {
    USERS_SEEDED: 'USERS_SEEDED'
};

export const ERROR_RESPONSES = {
    PLEASE_TRY_AGAIN: 'PLEASE_TRY_AGAIN',
    EMAIL_IS_REQUIRED: 'EMAIL_IS_REQUIRED',
    PASSWORD_IS_REQUIRED:  'PASSWORD_IS_REQUIRED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_PASSWORD: 'INVALID_PASSWORD'
};